<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-D8GBQRP8" name="com.platformX.tests.QA_019_Neuspjesno_Dodavanje_Ugovora_Test6" tests="1" failures="1" timestamp="07 feb 2021 19:41:01 GMT" time="66.210" errors="0">
  <testcase name="qa_019_nesupjesno_dodavanje_ugovora_test6" time="66.210" classname="com.platformX.tests.QA_019_Neuspjesno_Dodavanje_Ugovora_Test6">
    <failure type="java.lang.AssertionError" message="Ugovori: Poruka upozorenja nije dobra! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Ugovori: Poruka upozorenja nije dobra! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.platformX.page.UgovoriPage.verifikujPoruku(UgovoriPage.java:431)
	at com.platformX.tests.QA_019_Neuspjesno_Dodavanje_Ugovora_Test6.qa_019_nesupjesno_dodavanje_ugovora_test6(QA_019_Neuspjesno_Dodavanje_Ugovora_Test6.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- qa_019_nesupjesno_dodavanje_ugovora_test6 -->
</testsuite> <!-- com.platformX.tests.QA_019_Neuspjesno_Dodavanje_Ugovora_Test6 -->
